/** Shared records and commands for the authenticated, local enterprise workspace. */
import type { Branded } from '@deepseek-ai/dsh-brand';

/** Identifier admitted by the enterprise wire parser. */
export type EnterpriseId = Branded<'ClawMasterEnterpriseId'>;

/**
 * Apply the compile-time brand; the Host validates incoming identifiers.
 * @param value Identifier generated by the client.
 * @returns The identifier with its enterprise record brand.
 */
export function enterpriseId(value: string): EnterpriseId { return value as EnterpriseId; }

/** CRM contact fields supplied by a user. Dates use YYYY-MM-DD or null. */
export interface ContactInput {
  id: EnterpriseId;
  name: string;
  company: string;
  stage: 'lead' | 'contacted' | 'proposal' | 'won' | 'lost';
  nextAction: string;
  nextActionDate: string | null;
}

/** Persisted contact with its most recent change time. */
export interface Contact extends ContactInput { updatedAt: string; }

/** Stock counts are nonnegative safe integers; changes are recorded in the audit log. */
export interface InventoryItemInput {
  id: EnterpriseId;
  sku: string;
  name: string;
  stock: number;
  reorderAt: number;
  supplier: string;
}

/** Persisted SKU with its most recent change time. */
export interface InventoryItem extends InventoryItemInput { updatedAt: string; }

/** One order line; money is an integer in the currency's minor unit. */
export interface OrderLine {
  itemId: EnterpriseId;
  quantity: number;
  unitPriceMinorUnits: number;
}

/** Editable purchase or sale order. Each SKU may occur only once. */
export interface OrderInput {
  id: EnterpriseId;
  kind: 'purchase' | 'sale';
  counterparty: string;
  orderDate: string;
  currency: 'CNY';
  lines: OrderLine[];
  note: string;
}

/** Submitted orders are immutable and their stock changes commit exactly once. */
export interface BusinessOrder extends OrderInput {
  status: 'draft' | 'submitted';
  totalMinorUnits: number;
  updatedAt: string;
  submittedAt: string | null;
}

/** One atomic business action; all mutations require the current snapshot revision. */
export type EnterpriseCommand =
  | { type: 'contact.upsert'; contact: ContactInput }
  | { type: 'contact.remove'; id: EnterpriseId }
  | { type: 'item.upsert'; item: InventoryItemInput }
  | { type: 'item.remove'; id: EnterpriseId }
  | { type: 'order.save'; order: OrderInput }
  | { type: 'order.remove'; id: EnterpriseId }
  | { type: 'order.submit'; id: EnterpriseId };

/** Retrying one commandId with the same command never repeats a mutation. */
export interface EnterpriseCommandRequest {
  revision: number;
  commandId: EnterpriseId;
  command: EnterpriseCommand;
}

/** Durable before/after facts committed in the same transaction as the command. */
export interface AuditEntry {
  revision: number;
  commandId: EnterpriseId;
  type: EnterpriseCommand['type'];
  entityId: EnterpriseId;
  at: string;
  before: unknown;
  after: unknown;
}

/** Complete local business state, independent of browser origin and selected Session. */
export interface EnterpriseSnapshot {
  revision: number;
  contacts: Contact[];
  inventory: InventoryItem[];
  orders: BusinessOrder[];
  audit: AuditEntry[];
}

/** Stable failure codes consumed by the UI; messages contain no SQL or filesystem paths. */
export type EnterpriseErrorCode = 'invalid_request' | 'revision_conflict' | 'command_conflict'
  | 'not_found' | 'duplicate_sku' | 'referenced_item' | 'submitted_order'
  | 'insufficient_stock' | 'numeric_overflow' | 'storage_unavailable' | 'storage_invalid';

/** Business failure with a stable client-safe code and optional current revision. */
export class EnterpriseError extends Error {
  readonly code: EnterpriseErrorCode;
  readonly currentRevision?: number;

  constructor(code: EnterpriseErrorCode, message: string, currentRevision?: number) {
    super(message);
    this.code = code;
    this.currentRevision = currentRevision;
    this.name = 'EnterpriseError';
  }
}

/** JSON error returned with an appropriate 4xx/5xx HTTP status. */
export interface EnterpriseErrorResponse {
  error: { code: EnterpriseErrorCode; message: string; currentRevision?: number };
}

/** Authenticated DSH Fetch routes owned by this module. */
export const ENTERPRISE_SNAPSHOT_PATH = '/api/clawmaster/enterprise';
/** Authenticated route for a complete enterprise backup envelope. */
export const ENTERPRISE_BACKUP_PATH = '/api/clawmaster/enterprise/backup';
/** Authenticated route for an explicitly confirmed enterprise restore. */
export const ENTERPRISE_RESTORE_PATH = '/api/clawmaster/enterprise/restore';
/** Authenticated command route; successful responses contain the committed snapshot. */
export const ENTERPRISE_COMMAND_PATH = '/api/clawmaster/enterprise/command';
