/** Locale-owned MDXEditor controls; interpolation tokens are resolved by the editor adapter. */

const english = {
  'contentArea.editableMarkdown': 'Note body',
  'toolbar.toggleGroup': 'toggle group',
  'toolbar.undo': 'Undo {{shortcut}}',
  'toolbar.redo': 'Redo {{shortcut}}',
  'toolbar.bold': 'Bold',
  'toolbar.removeBold': 'Remove bold',
  'toolbar.italic': 'Italic',
  'toolbar.removeItalic': 'Remove italic',
  'toolbar.inlineCode': 'Inline code format',
  'toolbar.removeInlineCode': 'Remove code format',
  'codeBlock.plainText': 'Plain text',
  'toolbar.blockTypes.paragraph': 'Paragraph',
  'toolbar.blockTypes.quote': 'Quote',
  'toolbar.blockTypes.heading': 'Heading {{level}}',
  'toolbar.blockTypeSelect.selectBlockTypeTooltip': 'Select block type',
  'toolbar.blockTypeSelect.placeholder': 'Block type',
  'toolbar.bulletedList': 'Bulleted list',
  'toolbar.numberedList': 'Numbered list',
  'toolbar.checkList': 'Check list',
  'toolbar.link': 'Create link',
  'toolbar.table': 'Insert Table',
  'toolbar.codeBlock': 'Insert Code Block',
  'toolbar.thematicBreak': 'Insert thematic break',
  'createLink.url': 'URL',
  'createLink.urlPlaceholder': 'Select or paste an URL',
  'createLink.textTooltip': 'The text to be displayed for the link',
  'createLink.text': 'Anchor text',
  'createLink.titleTooltip': "The link's title attribute, shown on hover",
  'createLink.title': 'Link title',
  'createLink.saveTooltip': 'Set URL',
  'createLink.cancelTooltip': 'Cancel change',
  'dialogControls.save': 'Save',
  'dialogControls.cancel': 'Cancel',
  'linkPreview.open': 'Open {{url}} in new window',
  'linkPreview.edit': 'Edit link URL',
  'linkPreview.copyToClipboard': 'Copy to clipboard',
  'linkPreview.copied': 'Copied!',
  'linkPreview.remove': 'Remove link',
  'table.deleteTable': 'Delete table',
  'table.columnMenu': 'Column menu',
  'table.rowMenu': 'Row menu',
  'table.textAlignment': 'Text alignment',
  'table.alignLeft': 'Align left',
  'table.alignCenter': 'Align center',
  'table.alignRight': 'Align right',
  'table.insertColumnLeft': 'Insert a column to the left of this one',
  'table.insertColumnRight': 'Insert a column to the right of this one',
  'table.deleteColumn': 'Delete this column',
  'table.insertRowAbove': 'Insert a row above this one',
  'table.insertRowBelow': 'Insert a row below this one',
  'table.deleteRow': 'Delete this row',
  'codeBlock.selectLanguage': 'Select code block language',
  'codeBlock.inlineLanguage': 'Language',
  'codeBlock.language': 'Code block language',
  'codeblock.delete': 'Delete code block',
} as const;

const chinese: { readonly [Key in keyof typeof english]: string } = {
  'contentArea.editableMarkdown': '笔记正文',
  'toolbar.toggleGroup': '格式选项',
  'toolbar.undo': '撤销 {{shortcut}}',
  'toolbar.redo': '重做 {{shortcut}}',
  'toolbar.bold': '加粗',
  'toolbar.removeBold': '取消加粗',
  'toolbar.italic': '斜体',
  'toolbar.removeItalic': '取消斜体',
  'toolbar.inlineCode': '行内代码',
  'toolbar.removeInlineCode': '取消代码格式',
  'codeBlock.plainText': '纯文本',
  'toolbar.blockTypes.paragraph': '正文',
  'toolbar.blockTypes.quote': '引用',
  'toolbar.blockTypes.heading': '{{level}} 级标题',
  'toolbar.blockTypeSelect.selectBlockTypeTooltip': '选择段落格式',
  'toolbar.blockTypeSelect.placeholder': '段落格式',
  'toolbar.bulletedList': '无序列表',
  'toolbar.numberedList': '有序列表',
  'toolbar.checkList': '任务列表',
  'toolbar.link': '创建链接',
  'toolbar.table': '插入表格',
  'toolbar.codeBlock': '插入代码块',
  'toolbar.thematicBreak': '插入分隔线',
  'createLink.url': '链接地址',
  'createLink.urlPlaceholder': '选择或粘贴链接地址',
  'createLink.textTooltip': '链接显示的文字',
  'createLink.text': '链接文字',
  'createLink.titleTooltip': '鼠标悬停时显示的链接标题',
  'createLink.title': '链接标题',
  'createLink.saveTooltip': '设置链接地址',
  'createLink.cancelTooltip': '取消修改',
  'dialogControls.save': '保存',
  'dialogControls.cancel': '取消',
  'linkPreview.open': '在新窗口打开 {{url}}',
  'linkPreview.edit': '编辑链接地址',
  'linkPreview.copyToClipboard': '复制到剪贴板',
  'linkPreview.copied': '已复制',
  'linkPreview.remove': '移除链接',
  'table.deleteTable': '删除表格',
  'table.columnMenu': '列操作',
  'table.rowMenu': '行操作',
  'table.textAlignment': '文字对齐方式',
  'table.alignLeft': '左对齐',
  'table.alignCenter': '居中对齐',
  'table.alignRight': '右对齐',
  'table.insertColumnLeft': '在此列左侧插入一列',
  'table.insertColumnRight': '在此列右侧插入一列',
  'table.deleteColumn': '删除此列',
  'table.insertRowAbove': '在此行上方插入一行',
  'table.insertRowBelow': '在此行下方插入一行',
  'table.deleteRow': '删除此行',
  'codeBlock.selectLanguage': '选择代码块语言',
  'codeBlock.inlineLanguage': '语言',
  'codeBlock.language': '代码块语言',
  'codeblock.delete': '删除代码块',
};

/**
 * Return the strings used by the Notes rich editor's enabled MDXEditor controls.
 * @param locale Product interface language.
 * @returns Translation templates keyed by MDXEditor identifiers, with interpolation tokens intact.
 */
export function notesRichCopy(locale: 'zh-CN' | 'en-US'): Readonly<Record<string, string>> {
  return locale === 'zh-CN' ? chinese : english;
}
